### ISSUE TITLE
Support Kubernetes as store backend

### ISSUE THREAD

**Issue by pedromvieira** [UnitedTraders/stolon-standby-haproxy#1]
Can we use this script with Stolon with Kubernetes as store backend?
We have a 3 node cluster similar to Stolon documentation for Kubernetes.

**Comment by strangeman** [comment]
Hello! Thank you for the interest to stolon-standby-haproxy!
Yes, it should be possible. This script talks with `stolonctl`, not with etcd or consul, so it can be used with any backend.
