### ISSUE TITLE
Stolon ha proxy clarification 

### ISSUE THREAD

**Issue by allenvino1** [UnitedTraders/stolon-standby-haproxy#2]
Hi I just wanna ask about this inplementation. 

Where Im I gonna run this inside stolon proxy or stolon replicas? The readme has an example of a service file, quite confused about the instructions. I’m  running my stolon on kubernetes. Thanks!

**Comment by strangeman** [comment]
Hi! This script interacts with `stolonctl` utility, so you can run it from any machine which has installed and properly configured `stolonctl`.
