### ISSUE TITLE
Need some details about connections.

### ISSUE THREAD

**Issue by sathyu** [UnitedTraders/stolon-standby-haproxy#3]
HI 

It is a great  thing to have haproxy on top stolon . Liked stolon for its auto HA.  
Can you please tell me how haproxy  knows  which connection is for read and which one is for write and forward the connection to either   standby (read only)  or master (read and write).

Thanks

**Comment by strangeman** [comment]
Sorry for the delay, was on vacation.
The script calls `stolonctl` binary and gets JSON with state of all stolon servers (healthy/unhealthy, master/standby, full command is `stolonctl clusterdata`). Then, it generates the HAProxy template (via jinja2, see https://github.com/UnitedTraders/stolon-standby-haproxy/blob/master/stolon_haproxy.j2) and reloads haproxy (see https://github.com/UnitedTraders/stolon-standby-haproxy/blob/master/config.yml).
