### ISSUE TITLE
After a failover, the program stops running

### ISSUE THREAD

**Issue by viggy28** [UnitedTraders/stolon-standby-haproxy#5]
After a failover, looks like for a few seconds the key **listenAddress** doesn't exist on cluster data.

Error log:

`Config not changed!
Config not changed!
Config not changed!
Traceback (most recent call last):
  File "src/main.py", line 53, in <module>
    database['status']['listenAddress'] + ':' + database['status']['port'])
KeyError: 'listenAddress'`

**Comment by viggy28** [comment]
will send a PR shortly.

**Comment by strangeman** [comment]
Thank you! I merged your PR, but looks like there is a more complex problem. Current logic is too fragile, at least need to add some exception handling.

**Comment by strangeman** [comment]
merged #4
